import type { Feature } from './types';

export const MOCK_FEATURES: Feature[] = [
  {
    id: 'feat-1',
    title: 'AI-Powered Feature Suggestions',
    description: 'Use ML to analyze user feedback and generate potential features.',
    status: 'In Progress',
    impact: 9,
    reach: 8,
    effort: 7,
    alignment: {
      salesEnablement: 6,
      customerRetention: 8,
      brandRecognition: 9,
    },
    owner: { name: 'Alice Johnson', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2024-09-15',
  },
  {
    id: 'feat-2',
    title: 'Advanced Data Import',
    description: 'Allow importing data from Zendesk and other sources.',
    status: 'Backlog',
    impact: 7,
    reach: 6,
    effort: 5,
    alignment: {
      salesEnablement: 8,
      customerRetention: 7,
      brandRecognition: 5,
    },
    owner: { name: 'Bob Williams', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2024-10-01',
  },
  {
    id: 'feat-3',
    title: 'Single Sign-On (SSO)',
    description: 'Integrate with major SSO providers like Okta and Auth0.',
    status: 'Completed',
    impact: 8,
    reach: 7,
    effort: 6,
    alignment: {
      salesEnablement: 9,
      customerRetention: 8,
      brandRecognition: 6,
    },
    owner: { name: 'Charlie Brown', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2024-07-20',
  },
  {
    id: 'feat-4',
    title: 'Public API Access',
    description: 'Provide a public API for developers to build integrations.',
    status: 'Backlog',
    impact: 8,
    reach: 9,
    effort: 8,
    alignment: {
      salesEnablement: 7,
      customerRetention: 8,
      brandRecognition: 9,
    },
    owner: { name: 'Diana Prince', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2024-11-10',
  },
   {
    id: 'feat-5',
    title: 'UI Theming Engine',
    description: 'Allow users to customize the app appearance with themes.',
    status: 'In Progress',
    impact: 5,
    reach: 4,
    effort: 4,
    alignment: {
      salesEnablement: 2,
      customerRetention: 6,
      brandRecognition: 7,
    },
    owner: { name: 'Ethan Hunt', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2024-09-30',
  },
  {
    id: 'feat-6',
    title: 'Mobile App for iOS',
    description: 'Develop a native iOS application for on-the-go access.',
    status: 'Backlog',
    impact: 10,
    reach: 10,
    effort: 10,
    alignment: {
      salesEnablement: 8,
      customerRetention: 10,
      brandRecognition: 10,
    },
    owner: { name: 'Fiona Glenanne', avatarUrl: 'https://placehold.co/40x40.png' },
    deadline: '2025-03-01',
  },
];
